prepare_target_temperature_test:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: proxon_hesp
    expected_temperature:
      required: true
      example: 21
      selector:
        number:
          min: 18
          max: 30
          step: 0.5
          mode: box
          unit_of_measurement: °C
    delta:
      required: true
      example: 0.5
      selector:
        number:
          min: -0.5
          max: 0.5
          step: 1
          mode: slider
          unit_of_measurement: °C
send_target_temperature_test:
  fields:
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: proxon_hesp
    confirmation_token:
      required: true
      selector:
        text:
